# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Carapace < Formula
  desc "multi-shell multi-command argument completer"
  homepage "https://github.com/carapace-sh/carapace-bin"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v1.0.4/carapace-bin_darwin_amd64.tar.gz"
      sha256 "a940e75491fb84bc8ed1a4671de2f37c8666153015edbd6c18313985fde98ef1"

      def install
        bin.install "carapace"
      end
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v1.0.4/carapace-bin_darwin_arm64.tar.gz"
      sha256 "9bf1a904e98ffae9a02f4b2c07aeef23800e14181468f3a04b6c3d3242da1620"

      def install
        bin.install "carapace"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/carapace-bin/releases/download/v1.0.4/carapace-bin_linux_amd64.tar.gz"
        sha256 "406ae192787c41fd7db974e3f3ac8a84d20bdb39e00219f5d89ac7fbbc1badce"

        def install
          bin.install "carapace"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/carapace-bin/releases/download/v1.0.4/carapace-bin_linux_arm64.tar.gz"
        sha256 "7546cb8fc73e1a6dddcf921497a1c89f0435145f1ab8f2fb8ba92544ee55b95e"

        def install
          bin.install "carapace"
        end
      end
    end
  end
end
