# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceMagick < Formula
  desc "An ImageMagick magick argstream lexer and completer."
  homepage "https://github.com/carapace-sh/carapace-magick"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/carapace-magick/releases/download/v0.0.1/carapace-magick_0.0.1_darwin_amd64.tar.gz"
      sha256 "1f11d40196ffb6543e185dc6e9eb5b264da91c82fefcef24e1f9136eb38a4e6c"

      define_method(:install) do
        bin.install "carapace-magick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/carapace-magick/releases/download/v0.0.1/carapace-magick_0.0.1_darwin_arm64.tar.gz"
      sha256 "c33ab499fd01299c37942b9ff78e5a9dabda49eb9955c09d02b226afa18a0c7b"

      define_method(:install) do
        bin.install "carapace-magick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-magick/releases/download/v0.0.1/carapace-magick_0.0.1_linux_amd64.tar.gz"
      sha256 "5bb943b8797b4e19569a2ea3ab514d4826de1996db236d6891e1c55a8c71e199"
      define_method(:install) do
        bin.install "carapace-magick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-magick/releases/download/v0.0.1/carapace-magick_0.0.1_linux_arm64.tar.gz"
      sha256 "30f4d8a5e3f3a0153467673db103a5f9ea3f619be0e5e5c064c21278fbf06942"
      define_method(:install) do
        bin.install "carapace-magick"
      end
    end
  end
end
