# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceAws < Formula
  desc "An enriched aws completer"
  homepage "https://github.com/carapace-sh/carapace-aws"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.3/carapace-aws_0.0.3_darwin_amd64.tar.gz"
      sha256 "1f95892566f24960e82f9e5dab43ece775314d7c8effbdd93faa38627605dbef"

      def install
        bin.install "carapace-aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.3/carapace-aws_0.0.3_darwin_arm64.tar.gz"
      sha256 "d0cd5b97a7d6000c972e47e948d39dfb2c6a543a2e8ac827a39fd843cfed8887"

      def install
        bin.install "carapace-aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.3/carapace-aws_0.0.3_linux_amd64.tar.gz"
      sha256 "00af255a0296650b3cc0ff3cb9cffe4ae00ff55f6dd8b0ce4821bba743457def"
      def install
        bin.install "carapace-aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.3/carapace-aws_0.0.3_linux_arm64.tar.gz"
      sha256 "8737ea3c2b6ec1900170a6cb29a4010c4977ff978e67f49f243ab0757e3adc67"
      def install
        bin.install "carapace-aws"
      end
    end
  end
end
