# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceSpecMan < Formula
  desc "generate spec from manpages"
  homepage "https://github.com/rsteube/carapace-spec-man"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-spec-man/releases/download/v0.0.3/carapace-spec-man_darwin_amd64.tar.gz"
      sha256 "c7110a9cf211e61d0de5b36e9b71a12e096a8e502cbcdbddeef7835885fab489"

      def install
        bin.install "carapace-spec-man"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/carapace-spec-man/releases/download/v0.0.3/carapace-spec-man_darwin_arm64.tar.gz"
      sha256 "58a30c35e8b3010d97c1dc67a57c174cab1a8064c0ecb624b08e905bcf4de2cc"

      def install
        bin.install "carapace-spec-man"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/carapace-spec-man/releases/download/v0.0.3/carapace-spec-man_linux_arm64.tar.gz"
      sha256 "5f36408d3a9a7430a10d669cc70b29739b170629a1989d76b554df4b02865410"

      def install
        bin.install "carapace-spec-man"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-spec-man/releases/download/v0.0.3/carapace-spec-man_linux_amd64.tar.gz"
      sha256 "6b576c83b6b020197ff8a7054d310776aaec0bdd45087c6fdfe9a2f9ffdd75d3"

      def install
        bin.install "carapace-spec-man"
      end
    end
  end
end
