# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceAws < Formula
  desc "An enriched aws completer"
  homepage "https://github.com/carapace-sh/carapace-aws"
  version "0.0.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.30/carapace-aws_0.0.30_darwin_amd64.tar.gz"
      sha256 "368ba2cf1908247b0f5f186c1d74a7d2c80e053c712b12f3da7367dc9619dc88"

      def install
        bin.install "carapace-aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.30/carapace-aws_0.0.30_darwin_arm64.tar.gz"
      sha256 "bcd4a38491c3005d1d57cc825bc8ced95bd86f939d2bdec25bc9c33cbafe0c50"

      def install
        bin.install "carapace-aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.30/carapace-aws_0.0.30_linux_amd64.tar.gz"
      sha256 "cdd7814668766454060cd0c34404233d25416a59d17e8b348716089e3a7a30f4"
      def install
        bin.install "carapace-aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-aws/releases/download/v0.0.30/carapace-aws_0.0.30_linux_arm64.tar.gz"
      sha256 "f9238d3df627c8251b6102ede8f92fcd53bc1a2344b2038b5392353af909179c"
      def install
        bin.install "carapace-aws"
      end
    end
  end
end
