# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceBridge < Formula
  desc "completion bridge"
  homepage "https://github.com/rsteube/carapace-bridge"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-bridge/releases/download/v0.0.18/carapace-bridge_darwin_amd64.tar.gz"
      sha256 "3315b98d2babcfaa9f64a6bf9c402558dd34ed36b8e4de4ec6852de6968c0377"

      def install
        bin.install "carapace-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/carapace-bridge/releases/download/v0.0.18/carapace-bridge_darwin_arm64.tar.gz"
      sha256 "f27b095dcab1f14024e525c553f48a9d0f606a9b8210112fcec761b648df397a"

      def install
        bin.install "carapace-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/carapace-bridge/releases/download/v0.0.18/carapace-bridge_linux_arm64.tar.gz"
      sha256 "4f5a02ea53ddf4a4f4041ec5322a2713eb66548123a2665223d3bc34865f22df"

      def install
        bin.install "carapace-bridge"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-bridge/releases/download/v0.0.18/carapace-bridge_linux_amd64.tar.gz"
      sha256 "f2e490ca75f355d5f62d12f24a9beaf64ae39ff5f74d4e83a4cbc7ed1a44f9c5"

      def install
        bin.install "carapace-bridge"
      end
    end
  end
end
