# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceSpec < Formula
  desc "define simple completions using a spec file"
  homepage "https://github.com/rsteube/carapace-spec"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.1.0/carapace-spec_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "e978d8d75cf2a70bb029054bcdfaf817bfd342e21ff62a29b793aafb5e0f0fa8"

      def install
        bin.install "carapace-spec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.1.0/carapace-spec_0.1.0_Darwin_arm64.tar.gz"
      sha256 "46f64fdcddab85a4c7851684bcc076e7e1b82e3cd6dd040f1cf408c66796f1f3"

      def install
        bin.install "carapace-spec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.1.0/carapace-spec_0.1.0_Linux_arm64.tar.gz"
      sha256 "c006eed45125fe7c84655ed4f504cd2c7cfe25b9a67a8595c1490944a10169d5"

      def install
        bin.install "carapace-spec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.1.0/carapace-spec_0.1.0_Linux_x86_64.tar.gz"
      sha256 "4c655aac76bdf1e82d610763f2ca4fc9badef7cb57b679a1e3892d16f3d6a467"

      def install
        bin.install "carapace-spec"
      end
    end
  end
end
