# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceBridge < Formula
  desc "A multi-shell completion bridge"
  homepage "https://github.com/carapace-sh/carapace-bridge"
  version "1.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v1.4.6/carapace-bridge_1.4.6_darwin_amd64.tar.gz"
      sha256 "d72f0ce87954a196e96304885a4a85292b68a969cc7cd9677ab4b4022567f61a"

      def install
        bin.install "carapace-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v1.4.6/carapace-bridge_1.4.6_darwin_arm64.tar.gz"
      sha256 "de916eed821896b2edfb1b6ae24a62037687aa54dca886bfca4cce91b90707dc"

      def install
        bin.install "carapace-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v1.4.6/carapace-bridge_1.4.6_linux_amd64.tar.gz"
      sha256 "81ba6be467e198249152f9f48da884afde822576c7d332d61c86d33c601e9720"
      def install
        bin.install "carapace-bridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v1.4.6/carapace-bridge_1.4.6_linux_arm64.tar.gz"
      sha256 "e1db937daadfe57eca70b10a88435b447b1cbd1d3b19b2ee9e4d191d85cf7264"
      def install
        bin.install "carapace-bridge"
      end
    end
  end
end
