# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceSpec < Formula
  desc "define simple completions using a spec file"
  homepage "https://github.com/rsteube/carapace-spec"
  version "0.6.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.6.6/carapace-spec_0.6.6_Darwin_arm64.tar.gz"
      sha256 "a3d55c367ade18c7fcf07817face4f591dddf41baf8af29c991ef74bd7d9707c"

      def install
        bin.install "carapace-spec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.6.6/carapace-spec_0.6.6_Darwin_x86_64.tar.gz"
      sha256 "bbe20999a2aa0c7d23d35c579d0ed641e108842f349518bca8dc88d28e5867e6"

      def install
        bin.install "carapace-spec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.6.6/carapace-spec_0.6.6_Linux_arm64.tar.gz"
      sha256 "3b6a2e74e459a2e1b309cb0a987a85e862f901a2d79dbc5db21f8dce6a60221e"

      def install
        bin.install "carapace-spec"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/carapace-spec/releases/download/v0.6.6/carapace-spec_0.6.6_Linux_x86_64.tar.gz"
      sha256 "962e74d3996a15c6d00815c0ee94731627633c5a3eaa529f197efa83a67061fb"

      def install
        bin.install "carapace-spec"
      end
    end
  end
end
