# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarapaceFfmpeg < Formula
  desc "An FFmpeg argstream lexer and completer."
  homepage "https://github.com/carapace-sh/carapace-ffmpeg"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/carapace-ffmpeg/releases/download/v0.0.8/carapace-ffmpeg_0.0.8_darwin_amd64.tar.gz"
      sha256 "d0fcb2898167e71db2809a775cf8f55c833bfefc4580f45e60bd6617537d993d"

      define_method(:install) do
        bin.install "carapace-ffmpeg"
        bin.install "carapace-ffplay"
        bin.install "carapace-ffprobe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/carapace-ffmpeg/releases/download/v0.0.8/carapace-ffmpeg_0.0.8_darwin_arm64.tar.gz"
      sha256 "5e7c632077b2562fb89defb42e6ee16559a560a8adef1f4d9b303bdfba1b7380"

      define_method(:install) do
        bin.install "carapace-ffmpeg"
        bin.install "carapace-ffplay"
        bin.install "carapace-ffprobe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-ffmpeg/releases/download/v0.0.8/carapace-ffmpeg_0.0.8_linux_amd64.tar.gz"
      sha256 "f595af5873a80bf5363e406b407caa335a4ce0f8e61cad98ef8f75df60c627e8"
      define_method(:install) do
        bin.install "carapace-ffmpeg"
        bin.install "carapace-ffplay"
        bin.install "carapace-ffprobe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carapace-sh/carapace-ffmpeg/releases/download/v0.0.8/carapace-ffmpeg_0.0.8_linux_arm64.tar.gz"
      sha256 "5c3517ea83a935a777c7c54edba33cc2e1839dc630061faab4791147858c3250"
      define_method(:install) do
        bin.install "carapace-ffmpeg"
        bin.install "carapace-ffplay"
        bin.install "carapace-ffprobe"
      end
    end
  end
end
