# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrecklesBin < Formula
  desc "simple dotfiles manager"
  homepage "https://github.com/rsteube/freckles-bin"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/freckles-bin/releases/download/v0.0.2/freckles-bin_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "a5567636b6e46592683fe2e4a8c7547f0ce75dd9522ffbac5ffb060eef6748c3"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/freckles-bin/releases/download/v0.0.2/freckles-bin_0.0.2_Darwin_arm64.tar.gz"
      sha256 "0f86fb92e11877ee362c364dbc8c01e7f3e384fcbe12c1a233d80790e49d69cb"

      def install
        bin.install "freckles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/freckles-bin/releases/download/v0.0.2/freckles-bin_0.0.2_Linux_arm64.tar.gz"
      sha256 "f1685603ddfc90e0cc7e01451408a6543942307d3260a2e53b53ff5f1b6e111e"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/freckles-bin/releases/download/v0.0.2/freckles-bin_0.0.2_Linux_x86_64.tar.gz"
      sha256 "48bdf537513911302314f0fac141045482529341f9af69350319d87d360dd9d7"

      def install
        bin.install "freckles"
      end
    end
  end
end
