# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freckles < Formula
  desc "A simple dotfile manager."
  homepage "https://github.com/carapace-sh/freckles"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/freckles/releases/download/v0.3.1/freckles_0.3.1_darwin_amd64.tar.gz"
      sha256 "657acf2149189f28acf721a082686cb80abd83af34d3b6faf14e8415993fab1f"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/freckles/releases/download/v0.3.1/freckles_0.3.1_darwin_arm64.tar.gz"
      sha256 "0d6e0aec3cc52b2ce421d2ffaa318bf5cbd16c9712f2f69fb588fbdc2f3825fe"

      def install
        bin.install "freckles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/freckles/releases/download/v0.3.1/freckles_0.3.1_linux_amd64.tar.gz"
        sha256 "119c9e56ce047843befab5b14f0ac63a95e47b7caa76d7dbd528f8b0a5d09593"

        def install
          bin.install "freckles"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/freckles/releases/download/v0.3.1/freckles_0.3.1_linux_arm64.tar.gz"
        sha256 "bbbc22d65574736ece5ed1472cc0f9b7e3bb4f7c8e6b95d3a7e7b536c95d509c"

        def install
          bin.install "freckles"
        end
      end
    end
  end
end
