# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freckles < Formula
  desc "A simple dotfile manager."
  homepage "https://github.com/carapace-sh/freckles"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/freckles/releases/download/v0.3.2/freckles_0.3.2_darwin_amd64.tar.gz"
      sha256 "8501dc4cc975376e549c18138bae8ba65d47cdac2cc40cd7691d40920b05d65b"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/freckles/releases/download/v0.3.2/freckles_0.3.2_darwin_arm64.tar.gz"
      sha256 "5429cd241afeaea36a2ba3989b66d37a4b7b836890e05b5365b642dccf31a938"

      def install
        bin.install "freckles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/freckles/releases/download/v0.3.2/freckles_0.3.2_linux_amd64.tar.gz"
        sha256 "6c03a10ddfae70c154d7d0adc3139e6eaaca901a10c28f9e8e5e937c9c85994e"

        def install
          bin.install "freckles"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/freckles/releases/download/v0.3.2/freckles_0.3.2_linux_arm64.tar.gz"
        sha256 "5c02c8ae0e671f675043195f8ca76760eeffddf5d1089cf74be8902e592d493e"

        def install
          bin.install "freckles"
        end
      end
    end
  end
end
