# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freckles < Formula
  desc "A simple dotfile manager."
  homepage "https://github.com/carapace-sh/freckles"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carapace-sh/freckles/releases/download/v0.3.0/freckles_0.3.0_darwin_amd64.tar.gz"
      sha256 "574920d4361fa5c4dbac4e128f01727e239079d16a7bf52d943d6aaa95fe21fa"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carapace-sh/freckles/releases/download/v0.3.0/freckles_0.3.0_darwin_arm64.tar.gz"
      sha256 "a4a071c577c5b949f2221a002c55530cbe75c1f185ee52a1f936f6a80d57a13a"

      def install
        bin.install "freckles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/freckles/releases/download/v0.3.0/freckles_0.3.0_linux_amd64.tar.gz"
        sha256 "4c2991a350406ef2788d1d090faa12b96d1a28427f88dd49f21ea0080c4dc467"

        def install
          bin.install "freckles"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/carapace-sh/freckles/releases/download/v0.3.0/freckles_0.3.0_linux_arm64.tar.gz"
        sha256 "668552dcd4827f44b5c12347a9eb94295d6d8223f5285db0959f18e780bc7fc0"

        def install
          bin.install "freckles"
        end
      end
    end
  end
end
