# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FrecklesBin < Formula
  desc "simple dotfiles manager"
  homepage "https://github.com/rsteube/freckles"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/freckles/releases/download/v0.0.3/freckles-bin_0.0.3_Darwin_arm64.tar.gz"
      sha256 "87d81b32a89829e3ef5e39156820144a866333233ef03125b8c8e5f9c5a5a14a"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/freckles/releases/download/v0.0.3/freckles-bin_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "ad2d033a942499d2ad08985b7c10550a2dd4a8400da1ed504d992ce117aab751"

      def install
        bin.install "freckles"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/freckles/releases/download/v0.0.3/freckles-bin_0.0.3_Linux_x86_64.tar.gz"
      sha256 "0835b4f1a9a8499456a013f18f022338ba80c4d4e7b6079c9865010f15ef99c4"

      def install
        bin.install "freckles"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/freckles/releases/download/v0.0.3/freckles-bin_0.0.3_Linux_arm64.tar.gz"
      sha256 "a7abe73575ecffa360271ac5ced72803ce7c7422cb594dca66d361d66130daee"

      def install
        bin.install "freckles"
      end
    end
  end
end
