# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoJiraCli < Formula
  desc "simple jira command line client"
  homepage "https://github.com/rsteube/go-jira-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.2.1/gj_0.2.1_Darwin_arm64.tar.gz"
      sha256 "2858ee576b95c3c9442c850c524b57587a25c33900cbfd0106311dbf5cf59f0f"

      def install
        bin.install "gj"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.2.1/gj_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "e040e9ec2c193e771c8650938e6b8c53c86050d94021070d0c1273c731926111"

      def install
        bin.install "gj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.2.1/gj_0.2.1_Linux_x86_64.tar.gz"
      sha256 "c803982dfaea4504c339d5cf77e07dd70391a120e6e4c347bc78465660f28307"

      def install
        bin.install "gj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.2.1/gj_0.2.1_Linux_arm64.tar.gz"
      sha256 "0f575fa22dcb79acd031e1bf8c07af26ffc1d3d9d7c4697b47ae094f097108e5"

      def install
        bin.install "gj"
      end
    end
  end
end
