# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoJiraCli < Formula
  desc "simple jira command line client"
  homepage "https://github.com/rsteube/go-jira-cli"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.1.11/gj_0.1.11_Darwin_x86_64.tar.gz"
      sha256 "9bb5c077b8fd5702096b5467390053e076828cee6641d5b3987dada748b2f0d3"

      def install
        bin.install "gj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.1.11/gj_0.1.11_Darwin_arm64.tar.gz"
      sha256 "4d0466c622d757d4d24898c1646268b082e3cc028fb63e359e4a7d4bb1f77ce8"

      def install
        bin.install "gj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.1.11/gj_0.1.11_Linux_x86_64.tar.gz"
      sha256 "bfbf14170e7fa08a49f59d38281b9b21e9d5838e10c4e106d2da486c676bb1b1"

      def install
        bin.install "gj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/go-jira-cli/releases/download/v0.1.11/gj_0.1.11_Linux_arm64.tar.gz"
      sha256 "2a28c69dc97e68bdade75bd0daa765dc58458ac5576e2dba7ea611005c8358ed"

      def install
        bin.install "gj"
      end
    end
  end
end
