# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycomplete < Formula
  desc "lazy loading for shell completion scripts"
  homepage "https://github.com/rsteube/lazycomplete"
  version "0.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/lazycomplete/releases/download/v0.0.18/lazycomplete_0.0.18_Darwin_x86_64.tar.gz"
      sha256 "eaca847af318e2091708e9966ec25a86ec3035f1da1cbf83fa817ad9b656e026"

      def install
        bin.install "lazycomplete"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/lazycomplete/releases/download/v0.0.18/lazycomplete_0.0.18_Darwin_arm64.tar.gz"
      sha256 "97a424b101246923e0fe63494211e2f9fdeedd32c38833ef94257a4bc65bcf24"

      def install
        bin.install "lazycomplete"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/lazycomplete/releases/download/v0.0.18/lazycomplete_0.0.18_Linux_x86_64.tar.gz"
      sha256 "89785be6a72a2f313edfb662c2c67dcd14bc8af1520513879c5f8b8c1df0a56f"

      def install
        bin.install "lazycomplete"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/lazycomplete/releases/download/v0.0.18/lazycomplete_0.0.18_Linux_arm64.tar.gz"
      sha256 "142a4b8fc75ab5673e5be51a93457dc6985f47e330431a9707bad9240c47448b"

      def install
        bin.install "lazycomplete"
      end
    end
  end
end
