# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vincent < Formula
  desc "terminal color theme chooser"
  homepage "https://github.com/rsteube/vincent"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.7/vincent_darwin_amd64.tar.gz"
      sha256 "68cec33fd7a8d525d3f519e2b296011d62903466262c8ce17da3021f4eee81fd"

      def install
        bin.install "vincent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.7/vincent_darwin_arm64.tar.gz"
      sha256 "a139451a719682ddb616885155f403fc90cde4685ea29fc51353c899574b31f3"

      def install
        bin.install "vincent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.7/vincent_linux_arm64.tar.gz"
      sha256 "df11f9b21ec35ca0d453a2166163ee113e96c7e752a2adb6e016b64fef630225"

      def install
        bin.install "vincent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.7/vincent_linux_amd64.tar.gz"
      sha256 "d47b3fb1345705b88ba76a069b6d3ccef757593c8445d8429df4c030339c26bc"

      def install
        bin.install "vincent"
      end
    end
  end
end
