# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vincent < Formula
  desc "terminal color theme chooser"
  homepage "https://github.com/rsteube/vincent"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.6/vincent_darwin_arm64.tar.gz"
      sha256 "f370e2bf2586742aa829418bbd23e58d3465c7a76898a3c7d521e1c921e98e87"

      def install
        bin.install "vincent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.6/vincent_darwin_amd64.tar.gz"
      sha256 "a878a749757df1623943a7080ec041ff2a26f1e332555677ee9be9d756e9d197"

      def install
        bin.install "vincent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.6/vincent_linux_amd64.tar.gz"
      sha256 "fd9ee4636e82ae880fe562c6c735350da86f13a1ac08a2ec212198078ac6111f"

      def install
        bin.install "vincent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/vincent/releases/download/v0.0.6/vincent_linux_arm64.tar.gz"
      sha256 "218e605301ac0df1c3321bb73c5e1ccd718dae1cb4513d2d889ca392515f1fba"

      def install
        bin.install "vincent"
      end
    end
  end
end
