# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vincent < Formula
  desc "terminal color theme chooser"
  homepage "https://github.com/rsteube/vincent"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/vincent/releases/download/v0.1.1/vincent_darwin_amd64.tar.gz"
      sha256 "f42c8bf6f73b167b150eb50e761a3c83dfc27204b9eac1110c1d1248d20ab863"

      def install
        bin.install "vincent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rsteube/vincent/releases/download/v0.1.1/vincent_darwin_arm64.tar.gz"
      sha256 "e23c83f1eb990bbc901d156158d5ebe14a2b398ccf3ceacfac794546b8599a3f"

      def install
        bin.install "vincent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rsteube/vincent/releases/download/v0.1.1/vincent_linux_arm64.tar.gz"
      sha256 "ddd1e9dedbaefea9bad6417dee6ddc15a91c016dcc28dc66b26a3f5b47f93492"

      def install
        bin.install "vincent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rsteube/vincent/releases/download/v0.1.1/vincent_linux_amd64.tar.gz"
      sha256 "99f1b4f5cf2d68f04bcb61e5a5edfb52d463cb634826a9689beb033e81e766bd"

      def install
        bin.install "vincent"
      end
    end
  end
end
