# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace-bridge" do
  name "carapace-bridge"
  desc "A multi-shell completion bridge"
  homepage "https://github.com/carapace-sh/carapace-bridge"
  version "1.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace-bridge"

  on_macos do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_darwin_amd64.tar.gz"
      sha256 "4b52b7a1a11f2fd5efd7b20f92f125073c0b070d8246adce16cfc43c286569a3"
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_darwin_arm64.tar.gz"
      sha256 "59b1ce236a855be2f37a4b08a330a4bf705bdce991379a14af9374bab64a71d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_linux_amd64.tar.gz"
      sha256 "ed0f858e6a3e225e19dd6266f6ba2fbe7ff3cc1919be07052f6016d694bd507a"
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_linux_arm64.tar.gz"
      sha256 "782216a9f846cbdccc4083941092f07b73788b08cc1516fcb75baf47cfef0f26"
    end
  end

  # No zap stanza required
end
