# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace-bridge" do
  version "1.6.3"

  on_macos do
    on_intel do
      sha256 "2ae591e3ee17e9bd9d7e7f4ec19f714926065844672460185aef234c3acef36e"
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd0a6db064e5193a9019bdd97fea7c03b6f0c6d7d336f76c237bc90f092140b7"
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "826dfc33a87264abeaee6591d58f3a648d6ca9f27b9bea6ef0fa1584d903cfa6"
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbf037cfa26211bc9f6eaf12cb6466326f6e078dff910b6c5169d32faceedc6d"
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carapace-bridge"
  desc "A multi-shell completion bridge"
  homepage "https://github.com/carapace-sh/carapace-bridge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace-bridge"

  # No zap stanza required

end
