# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace-gcloud" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "f3f240edad52d5f18149b9ad6c3e9cfbc35dd1011c57cd50b3646634ba7d339b"
      url "https://github.com/carapace-sh/carapace-gcloud/releases/download/v#{version}/carapace-gcloud_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "85186e2016c05e38b3ab5af398c5b4e4d3073537d97bc27ec72d1068c2156443"
      url "https://github.com/carapace-sh/carapace-gcloud/releases/download/v#{version}/carapace-gcloud_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2ff6544bf54fd8c20d4dc8ecceb0a35ea9be24754b158a15c64de83c003682a4"
      url "https://github.com/carapace-sh/carapace-gcloud/releases/download/v#{version}/carapace-gcloud_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d023a60fbc1ecebd10bf55da512584767eecc169955d42b6de2a75ff6bd7f6f"
      url "https://github.com/carapace-sh/carapace-gcloud/releases/download/v#{version}/carapace-gcloud_#{version}_linux_amd64.tar.gz"
    end
  end

  name "carapace-gcloud"
  desc "An enriched gcloud completer"
  homepage "https://github.com/carapace-sh/carapace-gcloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace-gcloud"

  # No zap stanza required
end
