# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace" do
  version "1.6.5"

  on_macos do
    on_intel do
      sha256 "e014371c670ff9e18d6e93ac0b0a97455a2999a40d8eb1784e8778a6e66b4ed1"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9715c3c0898e25b544dbb8768cc6727f82fc9e7d3ef35225dbaa9d6363452a53"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "02bd7c8975d590c04fdea1fe0ae918f616c53b1c5e0b723deb798efa8504d812"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6cd10d6b41322a7f3bc1688ed25ebcdee9849a293efaedf36523a1df2d81b1d0"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carapace"
  desc "A multi-shell completion binary"
  homepage "https://github.com/carapace-sh/carapace-bin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace"

  # No zap stanza required

end
