# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace-az" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "86e59799666b008cebb35bca2c21b4ab644bb5c62b0225814fa7e0d1f4737bbc"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8a3b016aec1d116b10c5852839d2264199b76b32e972f6cc74ef8cc4592652d5"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "09a3ff9edbfcd17a95683c850226c33bab8dee3c4699123fb3bdf8f087018ba8"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "09ba159411502a423818063c6b80e66189d8c5dbbfabd37e0e44c8fd3efb7960"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_linux_amd64.tar.gz"
    end
  end

  name "carapace-az"
  desc "An enriched az completer"
  homepage "https://github.com/carapace-sh/carapace-az"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace-az"

  # No zap stanza required
end
