# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace" do
  name "carapace"
  desc "A multi-shell completion binary"
  homepage "https://github.com/carapace-sh/carapace-bin"
  version "1.5.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace"

  on_macos do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_darwin_amd64.tar.gz"
      sha256 "7dc2b39ac27a6cf3f00cee81262d56738e036497991a23dcf50d839a91b3b5a3"
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_darwin_arm64.tar.gz"
      sha256 "892151c15d6fcb823662ae779198af177ee4e4230028201860334a330b7973d9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_linux_amd64.tar.gz"
      sha256 "5daf51d5867b0995aad94faa07c783fb083aa00723d2b9a31b177c21f197306f"
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_linux_arm64.tar.gz"
      sha256 "591d616f57b9d96de3925514ed95fede9fd754c7731278a50d8b1933619838c5"
    end
  end

  # No zap stanza required
end
