# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace" do
  version "1.7.1"

  on_macos do
    on_intel do
      sha256 "7156ac36fa5b00ba48187c84d3ea3942fe91bb3f49f82cc04448cda98249b93c"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66d1cba860026c53b8d93b6824e35f1127324efbf764b2aa6cf8f5e9cfdb78de"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c6823f49354faae99947a8dae377f7d96c5c9b67c596013b1a7bd68b40fffed"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1c864c05dae0cc44aa7f50d51c4ddb5d8b2e78c4f25846f68cb4c6cd250ca20"
      url "https://github.com/carapace-sh/carapace-bin/releases/download/v#{version}/carapace-bin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carapace"
  desc "A multi-shell completion binary"
  homepage "https://github.com/carapace-sh/carapace-bin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace"

  # No zap stanza required

end
