# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace-bridge" do
  name "carapace-bridge"
  desc "A multi-shell completion bridge"
  homepage "https://github.com/carapace-sh/carapace-bridge"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace-bridge"

  on_macos do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_darwin_amd64.tar.gz"
      sha256 "421f74471078c734eccb8a308135772462ad0283430eaf2d4dc47d4226a80c0e"
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_darwin_arm64.tar.gz"
      sha256 "78d5188bac786976015c9b49f52400a317719706a7aa9cb982fe914abe7388a8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_linux_amd64.tar.gz"
      sha256 "f00873b220216f34d4549bb12d05318333e1ef8b88bc58ffa81f4fb3a9126b9d"
    end
    on_arm do
      url "https://github.com/carapace-sh/carapace-bridge/releases/download/v#{version}/carapace-bridge_#{version}_linux_arm64.tar.gz"
      sha256 "66c9f991e86169d483b9f39e3772dbabf668f235e61f9e90f3bcdfb9c16a5055"
    end
  end

  # No zap stanza required
end
