# This file was generated by GoReleaser. DO NOT EDIT.
cask "carapace-az" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "cef00e9f89c3a9d7c78b2d0fba8c0ddc27ebcddcac99882d4b1e4fd1684c6cd9"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "42a8e5781935c5170fe05eaf89dbc004c29ddfc681ded06476b2a8ae1d4a72aa"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "819cd15c6ce26fef565a44e462632b2836b8c2604f12c8ce1c660dd864d02384"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "489d4d65357e6546f39dd227c22fa3c095e408851fe50b0bc804f4ae40150b13"
      url "https://github.com/carapace-sh/carapace-az/releases/download/v#{version}/carapace-az_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carapace-az"
  desc "An enriched az completer"
  homepage "https://github.com/carapace-sh/carapace-az"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carapace-az"

  # No zap stanza required

end
